spring:
  application:
    name: security-oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_nacos?serverTimezone=UTC
    username: zhou
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8030

#security:
#  oauth2:
#    sso:
#      login-path: /login
#    client:
#      client-id:
#      client-secret:
#      user-authorization-uri: http://127.0.0.1:8030/oauth/authorize    #直接配置认证中心端口(http://127.0.0.1:9200/oauth/authorize)，也可以配置网关端口
#      access-token-uri: http://127.0.0.1:8030/oauth/token              #直接配置认证中心端口(http://127.0.0.1:9200/oauth/authorize)，也可以配置网关端口
#    resource:
#      token-info-uri: http://127.0.0.1:8030/oauth/check_token          #直接配置认证中心端口(http://127.0.0.1:9200/oauth/authorize)，也可以配置网关端口
#      prefer-token-info: true
