spring:
  application:
    name: service-monitoring
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: '*'